build: pnpm

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,18 +36,23 @@ jobs:
         id: detect-package-manager
         run: |
           if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
+              echo "manager=yarn" >> $GITHUB_OUTPUT
+              echo "command=install" >> $GITHUB_OUTPUT
+              echo "runner=yarn" >> $GITHUB_OUTPUT
+              exit 0
           elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
+              echo "manager=npm" >> $GITHUB_OUTPUT
+              echo "command=ci" >> $GITHUB_OUTPUT
+              echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+              exit 0
+          elif [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+              echo "manager=pnpm" >> $GITHUB_OUTPUT
+              echo "command=install" >> $GITHUB_OUTPUT
+              echo "runner=pnpm" >> $GITHUB_OUTPUT
+              exit 0
           else
-            echo "Unable to determine package manager"
-            exit 1
+              echo "Unable to determine package manager"
+              exit 1
           fi
 
       - name: Setup Node
